[package]
name = "tokio"
version = "0.1.0"
authors = ["Harapan21 <harapanpardamean@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version =  "1.4.0", features=["attributes"] }
